[TASK] Add the option to anonymize the IP address
networkteam/sentry_client pull request #58
Opened 2022-03-02 09:03 UTC by extcode

Resolves: #57

2022-04-11 10:58 UTC, christophlehmann requested changes

2022-04-11 10:58 UTC, christophlehmann commented on Classes/Client.php
> +        $ipAddress = GeneralUtility::getIndpEnv('REMOTE_ADDR');
`GeneralUtility::getIndpEnv('REMOTE_ADDR') ?: '127.0.0.1';` is fine here, so next if can be dropped.

2022-04-11 10:58 UTC, christophlehmann commented on Classes/Client.php
> +        return IpAnonymizationUtility::anonymizeIp($ipAddress, $ipMask);
It's fine for me to anonymize the IP. 
Let's do it with core behaviour and do not pass `$ipMask` here. Then `$GLOBALS['TYPO3_CONF_VARS']['SYS']['ipAnonymization']` is taken into account, which should be enough. 

Your new setting then can be dropped and the complete function can be replaced with `$userContext['ip_address'] = IpAnonymizationUtility::anonymizeIp(GeneralUtility::getIndpEnv('REMOTE_ADDR') ?? '127.0.0.1')`

2022-04-11 10:58 UTC, christophlehmann commented on ext_emconf.php
> +    'version' => '4.1.0',
In general developers who are not able to make a new release should not raise version numbers, because they don't know what's on the roadmap for a new release and it could also be a major release ;-) So this needs to stay at 4.0.1

2022-04-11 10:58 UTC, christophlehmann commented on README.md
> +For masking/anonymizing the IP address \TYPO3\CMS\Core\Utility\IpAnonymizationUtility::anonymizeIp()
This block can be dropped, too.

2022-04-11 11:20 UTC, extcode commented on Classes/Client.php
> +        return IpAnonymizationUtility::anonymizeIp($ipAddress, $ipMask);
Removed the function in class and remove explicit ip mask configuration for this package.

2022-04-11 11:20 UTC, extcode commented on ext_emconf.php
> +    'version' => '4.1.0',
Change version back to 4.0.1.

2022-04-12 19:05 UTC, extcode commented on README.md
> +For masking/anonymizing the IP address \TYPO3\CMS\Core\Utility\IpAnonymizationUtility::anonymizeIp()
Removed

2022-04-14 07:36 UTC, merged